ps_science_platform:
    resource: "@PSSciencePlatformBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: PSUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout